// A stand-in for CookPilot's two RecipePrinter parser endpoints, so browser
// tests exercise the real /api/parse route without reaching the real parser
// (which fetches through a paid scraper). Started by playwright.config.ts.
//
//   POST /parse-url   like recipePrinterParseRecipeFromURL: answers any URL with
//                     fixtures/cookpilot-reply.json, generated by running
//                     CookPilot's real parser on a fixture recipe page.
//   POST /parse-html  like recipePrinterParseSuppliedHTML: always "no recipe",
//                     so a test notices if the route ever falls through to it.
//   POST /<project>/<region>/checkUserProviders
//                     CookPilot's callable, in the callable wire format, since
//                     the browser reaches it through connectFunctionsEmulator.
//                     An email starting "returning" has a password account (the
//                     tests create it in the Auth emulator); any other is new.
//   GET  /health      for Playwright's readiness wait.

import { createServer } from "node:http";
import { readFileSync } from "node:fs";

const PORT = Number(process.env.COOKPILOT_STUB_PORT ?? 3211);
const SECRET = process.env.RECIPEPRINTER_PARSER_SECRET ?? "e2e-parser-secret";
const reply = readFileSync(new URL("../fixtures/cookpilot-reply.json", import.meta.url), "utf8");

// The browser calls the callable cross-origin (app on :3210, this on :3211).
const CORS = {
  "access-control-allow-origin": "*",
  "access-control-allow-headers": "content-type, authorization, x-firebase-appcheck, x-firebase-gmpid, x-firebase-client",
  "access-control-allow-methods": "POST, OPTIONS",
};

function send(res, status, body) {
  res.writeHead(status, { "content-type": "application/json", ...CORS });
  res.end(typeof body === "string" ? body : JSON.stringify(body));
}

createServer((req, res) => {
  if (req.method === "GET" && req.url === "/health") return send(res, 200, { ok: true });
  if (req.method === "OPTIONS") {
    res.writeHead(204, CORS);
    return res.end();
  }
  if (req.method === "POST" && req.url?.endsWith("/checkUserProviders")) {
    let raw = "";
    req.on("data", (chunk) => (raw += chunk));
    req.on("end", () => {
      const email = String(JSON.parse(raw || "{}")?.data?.email ?? "").toLowerCase();
      send(res, 200, { result: { providers: email.startsWith("returning") ? ["password"] : [] } });
    });
    return;
  }
  if (req.method !== "POST") return send(res, 405, { error: "Method not allowed" });
  if (req.headers["x-recipeprinter-parser-secret"] !== SECRET) return send(res, 401, { error: "Unauthorized" });
  req.resume();
  req.on("end", () => {
    if (req.url === "/parse-url") return send(res, 200, reply);
    if (req.url === "/parse-html") return send(res, 422, { error: "No recipe found on that page", verdict: { kind: "none" } });
    send(res, 404, { error: "Not found" });
  });
}).listen(PORT, "127.0.0.1", () => console.log(`cookpilot stub on :${PORT}`));
